from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UI_STORE = ROOT / "ui" / "src" / "store"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from server.openapi import build_openapi_spec


CLIENT_TEMPLATE = """// This file is generated by scripts/generate_openapi_client.py. Do not edit by hand.

export type ApiPath =
  | '/api/health'
  | '/api/openapi.json'
  | '/api/traces'
  | '/api/traces/import'
  | '/api/compare'
  | '/api/replay-jobs'
  | '/api/replay-dead-letters'
  | '/api/telemetry/events'
  | '/api/eval-cases'
  | '/api/eval-cases/from-trace'
  | '/api/eval-runs'
  | '/api/admin/governance/retention'
  | '/api/admin/governance/retention/apply'
  | '/api/admin/audit-events';

export type ApiMethod = 'GET' | 'POST';

export type GeneratedClientConfig = {
  baseUrl: string;
  tenantId: string;
  actorId: string;
  apiKey?: string;
};

export async function generatedApiRequest<T>(
  config: GeneratedClientConfig,
  path: ApiPath,
  method: ApiMethod,
  payload?: unknown,
  headers?: Record<string, string>
): Promise<T | null> {
  const requestHeaders: Record<string, string> = {
    'X-Tenant-Id': config.tenantId,
    'X-Actor-Id': config.actorId,
    ...headers,
  };
  if (config.apiKey) requestHeaders['X-API-Key'] = config.apiKey;
  if (payload !== undefined) requestHeaders['Content-Type'] = 'application/json';

  try {
    const response = await fetch(`${config.baseUrl}${path}`, {
      method,
      headers: requestHeaders,
      body: payload === undefined ? undefined : JSON.stringify(payload),
    });
    if (!response.ok) return null;
    return (await response.json()) as T;
  } catch {
    return null;
  }
}
"""


def main() -> None:
    UI_STORE.mkdir(parents=True, exist_ok=True)
    spec_path = UI_STORE / "openapi.generated.json"
    client_path = UI_STORE / "apiClient.generated.ts"

    spec = build_openapi_spec()
    spec_path.write_text(json.dumps(spec, indent=2), encoding="utf-8")
    client_path.write_text(CLIENT_TEMPLATE, encoding="utf-8")
    print(f"Wrote {spec_path}")
    print(f"Wrote {client_path}")


if __name__ == "__main__":
    main()
